// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8qmY0DC3tRKcyV0r8YXmymr-c1y78r0Y',
    appId: '1:422246535912:web:b9fb40db672516fa2cef5d',
    messagingSenderId: '422246535912',
    projectId: 'quranirab-74bba',
    authDomain: 'quranirab-74bba.firebaseapp.com',
    databaseURL: 'https://quranirab-74bba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quranirab-74bba.appspot.com',
    measurementId: 'G-GF36EVS4JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPLRqHyrGSqjCYyOMTcT923YnfVvDrq3k',
    appId: '1:422246535912:android:89f696f5b048ac762cef5d',
    messagingSenderId: '422246535912',
    projectId: 'quranirab-74bba',
    databaseURL: 'https://quranirab-74bba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quranirab-74bba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX3p_ji1RaDUKrp3xL6nYPKYR9CO8Grm0',
    appId: '1:422246535912:ios:7bd230e48c31a9112cef5d',
    messagingSenderId: '422246535912',
    projectId: 'quranirab-74bba',
    databaseURL: 'https://quranirab-74bba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quranirab-74bba.appspot.com',
    iosClientId: '422246535912-79okgi32a5smdl9btj6sc70a7fd0muso.apps.googleusercontent.com',
    iosBundleId: 'com.aqwise.quranirab.multiquranirab',
  );
}
